### ISSUE TITLE
Level doesn't save

### ISSUE THREAD

**Issue by Creeperface01** [williamtdr/Katana#24]
When i unload and load chunk so it doesn't save

**Comment by PEMapModder** [comment]
Got auto save on?
Anyway, Katana is for minigame servers.

**Comment by xxFlare** [comment]
@PEMapModder @Creeperface01 Chunks are cached, there not supposed to be saved.

@Creeperface01 As, PEMapModder said this is mainly for game servers.

**Comment by Creeperface01** [comment]
So you think i bedwars/annihilation/the walls/ the bridges etc.  Should be without block saving? xD
It would be great  ;)

**Comment by KnownUnown** [comment]
This is for our purposes, not yours, @Creeperface01. If you don't like it, build your own. We don't make BedWars. We don't make Bridges. We don't make all these other minigames. When and if we will, then we will evaluate the feasibility of this. Otherwise, no. Have a nice day.

**Comment by Creeperface01** [comment]
You said it is for minigames right?  And what about auto save

**Comment by linuzo** [comment]
It says in the readme

Warnings & Intentional Incompatibility

Katana does not support leveldb.
Katana does not use PocketMine's auto-updating or stats tracking systems.
Katana will only generate empty chunks for regions of the world that are not set.
Katana's default caching systems do not allow for worlds that are changed dynamically and saved (e.g. survival or player creative build worlds)
Katana performs reduced physics calculations.
Katana does not tick mob AIs.
Katana does not support packet channels.
Katana forces biome colors to be green. :rainbow:

**Comment by Creeperface01** [comment]
And williamtdr  made the walls

**Comment by KnownUnown** [comment]
Bahhhh 
Even so, we do __not__ reload chunks or worlds within the duration of the game. Also, see @linuzo's comment. This is a byproduct of the caching system, we are aware of it, and we do not need this feature.
